04-rails/cookbook/config/routes.rb
Rails.application.routes.draw do

  root 'pages#index' 
  get '/about' => 'pages#about'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy', :as => 'logout'

  resources :books
  resources :recipes
  resources :ingredients
end

04-rails/cookbook/app/models/book.rb
class Book < ActiveRecord::Base
  has_many :recipes

  def self.cuisines
    %w(french italian chinese japanese thai australian mexican korean)
  end

end

04-rails/cookbook/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many :recipes # many to many
end

04-rails/cookbook/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :book
  has_and_belongs_to_many :ingredients

  def self.meal_types
    %w(breakfast lunch dinner snack dessert)
  end

end

04-rails/cookbook/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, :uniqueness => true
end

04-rails/cookbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  private

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def authenticate
    redirect_to login_path unless logged_in?
  end
end

04-rails/cookbook/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path, :notice => 'new book successfully created'
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :cuisine, :image_url)
  end

end

04-rails/cookbook/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @books = Book.all
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

04-rails/cookbook/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate, :only => [:about]

  def index
  end

  def about
  end

end

04-rails/cookbook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @books = Book.all
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @books = Book.all
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :meal_type, :cooktime, :servingsize, :instructions, :image_url, :book_id, :ingredient_ids => [])
  end

end

04-rails/cookbook/app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authenticate

  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path, :notice => 'incorrect login or password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

04-rails/cookbook/app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control', :placeholder => 'your title' %>
  </div>
  <div class="form-group">
    <%= f.label :cuisine %>
    <%= f.select :cuisine, Book.cuisines, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image_url, 'bam for jam' %>
    <%= f.text_field :image_url, :class => 'form-control' %>
    <p class="help-block">This is actually the image URL.</p>
  </div>
  <button class="btn btn-primary">booook</button>

<% end %>

<!--form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form-->

04-rails/cookbook/app/views/books/edit.html.erb
<%= render 'form' %>

04-rails/cookbook/app/views/books/index.html.erb
<h1>Books List</h1>

<% @books.each do |book| %>
  <p><%= link_to book.title, book %> &nbsp;&nbsp;  
  <a href="<%= edit_book_path(book) %>"><span class="glyphicon glyphicon-edit"></span></a></p>
<% end %>

04-rails/cookbook/app/views/books/new.html.erb
<%= render 'form' %>

04-rails/cookbook/app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<% @book.recipes.each do |recipe| %>
  <p><%= link_to recipe.name, recipe %></p>
<% end %>

04-rails/cookbook/app/views/pages/about.html.erb
<h1>about</h1>

04-rails/cookbook/app/views/pages/index.html.erb
<h1>Home</h1>


<div class="row">

  <div class="col-sm-6 col-xs-12">
    <p><%= link_to 'new book', '/books/new', class: 'btn btn-primary' %></p>
  </div>

  <div class="col-sm-6 col-xs-12">
    <p><%= link_to 'new recipe', new_recipe_path, class: 'btn btn-primary' %></p>
  </div>

</div>